const arr = [
  {
    Kanji: "日",
    Onyomi: ["nichi, jitsu"],
    Kunyomi: ["hi, -bi, -ka"],
    Meaning: "day, sun, Japan, counter for days",
  },
  {
    Kanji: "一",
    Onyomi: ["ichi"],
    Kunyomi: ["hito(tsu)"],
    Meaning: "one",
  },
  {
    Kanji: "国",
    Onyomi: ["koku"],
    Kunyomi: ["kuni"],
    Meaning: "country",
  },
  {
    Kanji: "人",
    Onyomi: ["jin, nin"],
    Kunyomi: ["hito"],
    Meaning: "person",
  },
  {
    Kanji: "年",
    Onyomi: ["nen"],
    Kunyomi: ["toshi"],
    Meaning: "year, counter for years",
  },
  {
    Kanji: "大",
    Onyomi: ["dai, tai"],
    Kunyomi: ["oo(kii)"],
    Meaning: "large, big",
  },
  {
    Kanji: "十",
    Onyomi: ["juu"],
    Kunyomi: ["tou, to"],
    Meaning: "ten, 10",
  },
  {
    Kanji: "二",
    Onyomi: ["ni, ji"],
    Kunyomi: ["futa(tsu)"],
    Meaning: "two, 2",
  },
  {
    Kanji: "本",
    Onyomi: ["hon"],
    Kunyomi: ["moto"],
    Meaning: "book, present, true, counter for long cylindrical things",
  },
  {
    Kanji: "中",
    Onyomi: ["chuu"],
    Kunyomi: ["naka, uchi, ata(ru)"],
    Meaning: "in, inside, middle, mean, center",
  },
  {
    Kanji: "長",
    Onyomi: ["chou"],
    Kunyomi: ["naga(i), osa"],
    Meaning: "long, leader, superior, senior",
  },
  {
    Kanji: "出",
    Onyomi: ["shutsu, sui"],
    Kunyomi: ["de(ru), da(su), i(deru)"],
    Meaning: "exit, leave, go out",
  },
  {
    Kanji: "三",
    Onyomi: ["san"],
    Kunyomi: ["mi(tsu)"],
    Meaning: "three, 3",
  },
  {
    Kanji: "時",
    Onyomi: ["ji"],
    Kunyomi: ["toki, doki"],
    Meaning: "time, hour",
  },
  {
    Kanji: "行",
    Onyomi: ["kou, gyou, an"],
    Kunyomi: ["i(ku), yu(ku), okona(u)"],
    Meaning: "going, journey, carry out, line, row",
  },
  {
    Kanji: "見",
    Onyomi: ["ken"],
    Kunyomi: ["mi(ru), mi(seru)"],
    Meaning: "see, hopes, chances, idea, opinion, look at, visible",
  },
  {
    Kanji: "月",
    Onyomi: ["getsu, gatsu"],
    Kunyomi: ["tsuki"],
    Meaning: "month, moon",
  },
  {
    Kanji: "分",
    Onyomi: ["bun, fun, bu"],
    Kunyomi: ["wa(keru)"],
    Meaning: "part, minute of time, understand",
  },
  {
    Kanji: "後",
    Onyomi: ["go, kou"],
    Kunyomi: ["nochi, ushi(ro), ato"],
    Meaning: "behind, back, later",
  },
  {
    Kanji: "前",
    Onyomi: ["zen"],
    Kunyomi: ["mae"],
    Meaning: "in front, before",
  },
  {
    Kanji: "生",
    Onyomi: ["sei, shou"],
    Kunyomi: ["i(kiru), u(mu), o(u), ha(eru), nama"],
    Meaning: "life, genuine, birth",
  },
  {
    Kanji: "五",
    Onyomi: ["go"],
    Kunyomi: ["itsu(tsu)"],
    Meaning: "five, 5",
  },
  {
    Kanji: "間",
    Onyomi: ["kan, ken"],
    Kunyomi: ["aida, ma, ai"],
    Meaning: "interval, space",
  },
  {
    Kanji: "上",
    Onyomi: ["jou, shou, shan"],
    Kunyomi: ["ue, uwa, kami, a(geru), nobo(ru), tatematsu(ru)"],
    Meaning: "above, up",
  },
  {
    Kanji: "東",
    Onyomi: ["tou"],
    Kunyomi: ["higashi"],
    Meaning: "east",
  },
  {
    Kanji: "四",
    Onyomi: ["shi"],
    Kunyomi: ["yo(tsu), yon"],
    Meaning: "four, 4",
  },
  {
    Kanji: "今",
    Onyomi: ["kon, kin"],
    Kunyomi: ["ima"],
    Meaning: "now; the present",
  },
  {
    Kanji: "金",
    Onyomi: ["kin, kon, gon"],
    Kunyomi: ["kane, kana, gane"],
    Meaning: "gold",
  },
  {
    Kanji: "九",
    Onyomi: ["kyuu, ku"],
    Kunyomi: ["kokono(tsu)"],
    Meaning: "nine, 9",
  },
  {
    Kanji: "入",
    Onyomi: ["nyuu"],
    Kunyomi: ["i(ru), hai(ru)"],
    Meaning: "enter, insert",
  },
  {
    Kanji: "学",
    Onyomi: ["gaku"],
    Kunyomi: ["mana(bu)"],
    Meaning: "study, learning, science",
  },
  {
    Kanji: "高",
    Onyomi: ["kou"],
    Kunyomi: ["taka(i)"],
    Meaning: "tall, high, expensive",
  },
  {
    Kanji: "円",
    Onyomi: ["en"],
    Kunyomi: ["maru(i)"],
    Meaning: "circle, yen, round",
  },
  {
    Kanji: "子",
    Onyomi: ["shi, su, tsu"],
    Kunyomi: ["ko, ne"],
    Meaning: "child",
  },
  {
    Kanji: "外",
    Onyomi: ["gai, ge"],
    Kunyomi: ["soto, hoka, hazu-, to-"],
    Meaning: "outside",
  },
  {
    Kanji: "八",
    Onyomi: ["hachi"],
    Kunyomi: ["ya(tsu), you"],
    Meaning: "eight, 8",
  },
  {
    Kanji: "六",
    Onyomi: ["roku"],
    Kunyomi: ["mu(tsu), mui"],
    Meaning: "six, 6",
  },
  {
    Kanji: "下",
    Onyomi: ["ka, ge"],
    Kunyomi: ["shita, shimo, moto, sa(geru), kuda(ru), o(rosu)"],
    Meaning: "below, down, descend, give, low, inferior",
  },
  {
    Kanji: "来",
    Onyomi: ["rai, tai"],
    Kunyomi: ["kuru, kitaru, ki, ko"],
    Meaning: "come, due, next, cause, become",
  },
  {
    Kanji: "気",
    Onyomi: ["ki, ke"],
    Kunyomi: ["iki"],
    Meaning: "spirit, mind, air, atmosphere, mood",
  },
  {
    Kanji: "小",
    Onyomi: ["shou"],
    Kunyomi: ["chii(sai), ko-, o-, sa-"],
    Meaning: "little, small",
  },
  {
    Kanji: "七",
    Onyomi: ["shichi"],
    Kunyomi: ["nana(tsu), nano"],
    Meaning: "seven, 7",
  },
  {
    Kanji: "山",
    Onyomi: ["san, sen"],
    Kunyomi: ["yama"],
    Meaning: "mountain",
  },
  {
    Kanji: "話",
    Onyomi: ["wa"],
    Kunyomi: ["hana(su), hanashi"],
    Meaning: "tale, talk",
  },
  {
    Kanji: "女",
    Onyomi: ["jo"],
    Kunyomi: ["onnna, me"],
    Meaning: "woman, female",
  },
  {
    Kanji: "北",
    Onyomi: ["hoku"],
    Kunyomi: ["kita"],
    Meaning: "north",
  },
  {
    Kanji: "午",
    Onyomi: ["go"],
    Kunyomi: ["uma"],
    Meaning: "noon, sign of the horse",
  },
  {
    Kanji: "百",
    Onyomi: ["hyaku, byaku"],
    Kunyomi: ["momo"],
    Meaning: "hundred",
  },
  {
    Kanji: "書",
    Onyomi: ["sho"],
    Kunyomi: ["kaku"],
    Meaning: "write",
  },
  {
    Kanji: "先",
    Onyomi: ["sen"],
    Kunyomi: ["saki, ma(zu)"],
    Meaning: "before, ahead, previous, future, precedence",
  },
  {
    Kanji: "名",
    Onyomi: ["mei, myou"],
    Kunyomi: ["na"],
    Meaning: "name, noted, distinguished, reputation",
  },
  {
    Kanji: "川",
    Onyomi: ["sen"],
    Kunyomi: ["kawa"],
    Meaning: "river, stream",
  },
  {
    Kanji: "千",
    Onyomi: ["sen"],
    Kunyomi: ["chi"],
    Meaning: "thousand",
  },
  {
    Kanji: "水",
    Onyomi: ["sui"],
    Kunyomi: ["mizu"],
    Meaning: "water",
  },
  {
    Kanji: "半",
    Onyomi: ["han"],
    Kunyomi: ["naka(ba)"],
    Meaning: "half, middle, odd number, semi-",
  },
  {
    Kanji: "男",
    Onyomi: ["dan, nan"],
    Kunyomi: ["otoko, o"],
    Meaning: "male; man",
  },
  {
    Kanji: "西",
    Onyomi: ["sei, sai"],
    Kunyomi: ["nishi"],
    Meaning: "west",
  },
  {
    Kanji: "電",
    Onyomi: ["den"],
    Kunyomi: [],
    Meaning: "electricity; electric powered",
  },
  {
    Kanji: "校",
    Onyomi: ["kou"],
    Kunyomi: [],
    Meaning: "school, exam",
  },
  {
    Kanji: "語",
    Onyomi: ["go"],
    Kunyomi: ["kata(ru)"],
    Meaning: "word, speech, language",
  },
  {
    Kanji: "土",
    Onyomi: ["do, to"],
    Kunyomi: ["tsuchi"],
    Meaning: "soil, earth, ground",
  },
  {
    Kanji: "木",
    Onyomi: ["boku, moku"],
    Kunyomi: ["ki, ko"],
    Meaning: "tree, wood",
  },
  {
    Kanji: "聞",
    Onyomi: ["bun, mon"],
    Kunyomi: ["ki(ku)"],
    Meaning: "to hear; to listen; to ask",
  },
  {
    Kanji: "食",
    Onyomi: ["shoku, jiki"],
    Kunyomi: ["k(u), ta(beru), ha(mu)"],
    Meaning: "eat, food",
  },
  {
    Kanji: "車",
    Onyomi: ["sha"],
    Kunyomi: ["kuruma"],
    Meaning: "car, wheel",
  },
  {
    Kanji: "何",
    Onyomi: ["ka"],
    Kunyomi: ["nani, nan"],
    Meaning: "what",
  },
  {
    Kanji: "南",
    Onyomi: ["nan, na"],
    Kunyomi: ["minami"],
    Meaning: "south",
  },
  {
    Kanji: "万",
    Onyomi: ["man, ban"],
    Kunyomi: [],
    Meaning: "ten thousand, 10,000",
  },
  {
    Kanji: "毎",
    Onyomi: ["mai"],
    Kunyomi: ["goto(ni)"],
    Meaning: "every",
  },
  {
    Kanji: "白",
    Onyomi: ["haku, byaku"],
    Kunyomi: ["shiro(i)"],
    Meaning: "white",
  },
  {
    Kanji: "天",
    Onyomi: ["ten"],
    Kunyomi: ["amatsu"],
    Meaning: "heavens, sky, imperial",
  },
  {
    Kanji: "母",
    Onyomi: ["bo"],
    Kunyomi: ["haha, kaa"],
    Meaning: "mother",
  },
  {
    Kanji: "火",
    Onyomi: ["ka"],
    Kunyomi: ["hi, bi, ho"],
    Meaning: "fire",
  },
  {
    Kanji: "右",
    Onyomi: ["u, yuu"],
    Kunyomi: ["migi"],
    Meaning: "right (direction)",
  },
  {
    Kanji: "読",
    Onyomi: ["doku, toku, tou"],
    Kunyomi: ["yo(mu)"],
    Meaning: "to read",
  },
  {
    Kanji: "友",
    Onyomi: ["yuu"],
    Kunyomi: ["tomo"],
    Meaning: "friend",
  },
  {
    Kanji: "左",
    Onyomi: ["sa, sha"],
    Kunyomi: ["hidari"],
    Meaning: "left",
  },
  {
    Kanji: "休",
    Onyomi: ["kyuu"],
    Kunyomi: ["yasu(mu)"],
    Meaning: "rest, day off, retire, sleep",
  },
  {
    Kanji: "父",
    Onyomi: ["fu"],
    Kunyomi: ["chichi, tou"],
    Meaning: "father",
  },
  {
    Kanji: "雨",
    Onyomi: ["u"],
    Kunyomi: ["ame, ama"],
    Meaning: "rain",
  },
];

// function loopthroughArray(arr) {
//   arr.forEach((item, index) => {
//     if ((item["Meaning"] === "country")) {
//       console.log(index);
//     }
//     return item;
//   });
// }

for (i = 0; i < arr.length; i++) {
  if (arr[i].Meaning === "country") {
    console.log("Hi");
  }
}

